project: 
  type: website
  render:
    - "*.{qmd,m,py,ipynb}"
  
execute:
  freeze: true  # never re-execute computational content during project render, needed for .qmd and .rmd since quarto does not render .ipynb by default

website: 
  page-navigation: true
  title: "ASDC Data and User Services" 
  site-url: "https://nasa.github.io/ASDC_Data_and_User_Services/" 
  repo-url: https://github.com/nasa/ASDC_Data_and_User_Services
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "Atmospheric Science Data Center"
    
  sidebar:
    logo: "https://archive.ph/Np7yS/b8ad2ce6e0dc2019a56b06908e6a31d0dbb1d544.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://eosweb.larc.nasa.gov/
        text: "NASA ASDC Website"
      - icon: github
        href: https://github.com/nasa/ASDC_Data_and_User_Services
        text: "ASDC Data and User Services GitHub Repository"        

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - section: mission_notebooks.qmd
        text: Mission Tutorial Notebooks
        contents: 
          - section: DSCOVR
            contents:
            - text: DSCOVR UVAI Exploration
              href: DSCOVR/dscovr_uvai_exploration.ipynb
            - text: TEMPO UVAI vs DSCOVR (spatial)
              href: DSCOVR/tempo_uvai_vs_dscovr_spatial.ipynb
            - text: TEMPO UVAI vs DSCOVR vs AERONET
              href: DSCOVR/tempo_uvai_vs_dscovr_vs_aeronet.ipynb
          - section: MAIA
            contents:
            - text: MAIA netCDF Local Plotting
              href: MAIA/maia_netcdf_pm_python_local_plotting.ipynb
            - text: NetCDF to CSV Conversion
              href: MAIA/NetCDF2csv.ipynb
          - section: PREFIRE
            contents:
            - text: PREFIRE HyBIG
              href: PREFIRE/PREFIRE-HyBIG.ipynb
          - section: TEMPO
            contents:
            - text: Earthaccess Harmony
              href: TEMPO/earthaccess_harmony_01_2.ipynb
            - text: TEMPO with Harmony-py
              href: TEMPO/tempo_with_harmony-py_clean.ipynb
          - section: TOLNet
            contents:
            - text: TOLNet API Examples
              href: TOLNet/TOLNet_API_Examples_v01.ipynb
      - text: Mission Related Scripts (not notebooks)
        href: mission_scripts.qmd
      - learning-more.qmd


format:
  html:
    theme:
      light: cosmo # from https://quarto.org/docs/output-formats/html-themes.html
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true


# filters:
#   - include-files.lua
#   - quarto
