project: 
  type: website
  render:
    - "*.{qmd,m,py,ipynb}"
  
execute:
  freeze: true  # never re-execute computational content during project render, needed for .qmd and .rmd since quarto does not render .ipynb by default

website: 
  page-navigation: true
  title: "ASDC Data and User Services" 
  site-url: "https://nasa.github.io/ASDC_Data_and_User_Services/" 
  repo-url: https://github.com/nasa/ASDC_Data_and_User_Services
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "Atmospheric Science Data Center"
    
  sidebar:
    logo: "https://archive.ph/Np7yS/b8ad2ce6e0dc2019a56b06908e6a31d0dbb1d544.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://eosweb.larc.nasa.gov/
        text: "NASA ASDC Website"
      - icon: github
        href: https://github.com/nasa/ASDC_Data_and_User_Services
        text: "ASDC Data and User Services GitHub Repository"        

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - section: mission_notebooks.qmd
        text: Mission Tutorial Notebooks
        contents: 
          - section: DSCOVR
            contents:
            - text: Exploring EPIC aerosol data
              href: DSCOVR/how_to_explore_aerosol_data_from_EPIC_and_EPA-AQS.ipynb
            - text: Comparing TEMPO and DSCOVR aerosol data (spatially)
              href: DSCOVR/how_to_compare_spatially_TEMPO_with_DSCOVR_uvai.ipynb
            - text: Comparing TEMPO vs DSCOVR vs AERONET aerosol data
              href: DSCOVR/how_to_compare_TEMPO_with_DSCOVR_and_AERONET_uvai.ipynb
            - text: Computing daily average of EPIC Level-2 TO3 total ozone using OPeNDAP
              href: DSCOVR/how_to_compute_daily_averages_of_DSCOVR_EPIC_Level-2_TO3_total_ozone_using_OPeNDAP.ipynb
            - text: Computing daily average of EPIC Level-4 TrO3 using OPeNDAP
              href: DSCOVR/how_to_compute_daily_averages_of_DSCOVR_EPIC_Level-4_TrO3_Using_OPeNDAP.ipynb
          - section: MAIA
            contents:
            - text: MAIA netCDF Local Plotting
              href: MAIA/how_to_plot_map_of_MAIA_data_using_a_local_file.ipynb
            - text: NetCDF to CSV Conversion
              href: MAIA/how_to_convert_data_from_netCDF_to_csv_format.ipynb
          - section: PREFIRE
            contents:
            - text: PREFIRE HyBIG
              href: PREFIRE/how_to_generate_tiled_images_for_PREFIRE_using_HyBIG.ipynb
          - section: TEMPO
            contents:
            - text: Earthaccess Harmony
              href: TEMPO/examining_TEMPO_data_using_earthaccess_and_harmony-py.ipynb
            - text: TEMPO with Harmony-py
              href: TEMPO/how_to_visualize_TEMPO_data_using_harmony-py.ipynb
          - section: TOLNet
            contents:
            - text: TOLNet API Examples
              href: TOLNet/how_to_use_the_TOLNet_API_with_examples_of_plotting_and_GEOS-CF.ipynb
      - text: Mission Related Scripts (not notebooks)
        href: mission_scripts.qmd
      - learning-more.qmd


format:
  html:
    theme:
      light: cosmo # from https://quarto.org/docs/output-formats/html-themes.html
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true


# filters:
#   - include-files.lua
#   - quarto
